API integration...
Isla-del-Lago/isla-del-lago-web-ui pull request #14
Opened 2022-01-25 02:25 UTC by AlexanderLGRS

1. API integration
2. SWAL integration
3. Temporal Home page created
4. User register form validation
5. User login form validation

2022-01-26 13:22 UTC, JohanCamiloL requested changes

2022-01-26 13:22 UTC, JohanCamiloL commented on src/Pages/Login.jsx
> +        fetch('http://localhost:9000/api/v1/user/login',
Las URLs dejemolas en un modulo unico en el cual se puedan exportar, por ejemplo que usted la pueda usar así:
`URLs.baseUrl + /user/login`
El nombre URLs es opcional, le puede poner el nombre que quiera

2022-01-26 13:22 UTC, JohanCamiloL commented on src/Pages/Login.jsx
> +                    'Content-Type': 'application/json;charset=UTF-8'
El valor de los headers también los debemos parametrizar en un modulo aparte, para poderlos reutilizar en las otras peticiones que vamos a realizar durante la aplicación

2022-01-26 13:22 UTC, JohanCamiloL commented on src/Pages/Login.jsx
> +                    sessionStorage.setItem('uuid', response.uuid)
Los nombres de las llaves que se van a almacenar en el session storage también parametrizemolos en un modulo aparter para también poderlos usar con el mismo nombre en las demas partes de la aplicación

2022-01-26 13:22 UTC, JohanCamiloL commented on src/Pages/Login.jsx
> +                        document.location = '/'
¿Esta redirección no se puede hacer con Router? o esta bien hacer así con `document.location`

2022-01-26 13:22 UTC, JohanCamiloL commented on src/Pages/Register.jsx
> +            'http://localhost:9000/api/v1/user/create',
Los mismo comentarios que la pagina de Login, parametrizar los valores para reutilizarlos, aplica para URLs y valores de headers

2022-01-26 13:22 UTC, JohanCamiloL commented on src/Pages/Register.jsx
> +                console.table({ response });
No podemos pasar a los demas ambientes `console.log()`, solo se deben usar cuando este desarrollando y este haciendo pruebas en local

2022-01-27 00:40 UTC, AlexanderLGRS commented on src/Pages/Login.jsx
> +                        document.location = '/'
Asi está bien, he estado buscando otras opciones pero no encontré

2022-01-27 01:28 UTC, AlexanderLGRS commented
issues fixed

2022-01-27 01:38 UTC, JohanCamiloL approved these changes

2022-01-27 02:04 UTC, merged