Bill section
Isla-del-Lago/isla-del-lago-web-ui pull request #5
Opened 2021-09-30 02:06 UTC by AlexanderLGRS

1. All bill-forms are created and styled.
2. Input formats are verified.
3. POST method implemented.
4. SWAL implemented.

2021-09-30 02:56 UTC, JohanCamiloL requested changes

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/aqueduct-bill-info-form.jsx
> +        let m3RsdBsc = parseInt(this.m3RsdBsc.value)
Estos deberian ser constantes, no se esta actualizando el valor

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/aqueduct-bill-info-form2.jsx
> +        let acueFijoResd = parseFloat(this.acueFijoResd.value)
Manejar como constantes, no se esta actualizando el valor

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/javascripts/date.js
> +var today = new Date();
Evitar el uso de var, es mejor usar let por ejecuciones de bajo nivel de Javascript

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/principal-bill-info-form.jsx
> +        var dd = this.today.getDate();
Esta implementación también esta codificada en el archivo date.js, no es mejor reutilizar esa funcionalidad?

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/principal-bill-info-form.jsx
> +        if (this.startBillingDate.value === "" || this.endBillingDate.value === '' || this.discounts.value === '' || this.cleaning.value === '') {
Crear una variable por fuera del if para que ese condicional tan largo se pueda entender en lenguaje natural, por ejemplo 
`const isFormNotEmpty = this.startBillingDate.value === "" || this.endBillingDate.value === '' || this.discounts.value === '' || this.cleaning.value === ''

if (isFormNotEmpty) {
 ....
}`

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/sewer-bill-info.jsx
> +        this.API = 'http://localhost:8080/water/bill'
El valor del API lo puede inicializar en la variable de arriba, no es necesario que la inicialice en el componentDidMount() ya que no se esta necesitando que el DOM este renderizado para obtener algun valor

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/sewer-bill-info.jsx
> +        if (this.alcFijoResd.value === '' || this.alcRsdBsc.value === "" || this.alcRsdBscSup.value === '') {
Igual que el comentario de arriba, separe el condicional en una variable para que se entienda mas en lenguaje natural

2021-09-30 02:56 UTC, JohanCamiloL commented on src/components/sewer-bill-info.jsx
> +        this.datos = {
No es necesario que cree la variable a nivel de clase ya que solo la esta asignando una vez, la puede crear como una constante

2021-10-01 00:47 UTC, AlexanderLGRS commented on src/components/sewer-bill-info.jsx
> +        this.datos = {
En esta parte del código debo actualizar los últimos tres valores del form por que si lo hago antes los envía con valor "0".
Por eso deje el objeto "datos" dentro de la función submit

2021-10-06 01:18 UTC, merged